COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE = interrupt_streaming.c

API_LOCATION = ../..

C_SRCS += \
$(API_LOCATION)/bmi090la.c \
$(API_LOCATION)/bmi090lg.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

TARGET ?= MCU_APP20

include $(COINES_INSTALL_PATH)/coines.mk